const Langs = {
  en_US: {
    save: 'Save',
    copyMarkdown: 'Copy Markdown',
    copyHtml: 'Copy HTML',
    resetConfig: 'Reset config',
    resetConfirm: "Are you sure to reset the markdown-editor's config?",
    pageBreak: 'Page Break',
    headerFooter: 'Header & Footer',
    exportPdf: 'Export PDF',
    exportDocx: 'Export DOCX',
    pageSettings: 'Page Settings',
    pageSize: 'Page Size',
    header: 'Header',
    footer: 'Footer',
    pageNumbers: 'Page Numbers',
    pageNumberPosition: 'Page Number Position',
    none: 'None',
    left: 'Left',
    center: 'Center',
    right: 'Right',
    apply: 'Apply',
    cancel: 'Cancel',
    exportSuccess: 'Export successful!',
    exportError: 'Export failed',
  },
  ja_JP: {
    save: '保存する',
    pageBreak: '改ページ',
    headerFooter: 'ヘッダーとフッター',
    exportPdf: 'PDFにエクスポート',
    exportDocx: 'DOCXにエクスポート',
    pageSettings: 'ページ設定',
    pageSize: 'ページサイズ',
    header: 'ヘッダー',
    footer: 'フッター',
    pageNumbers: 'ページ番号',
    pageNumberPosition: 'ページ番号の位置',
    none: 'なし',
    left: '左',
    center: '中央',
    right: '右',
    apply: '適用',
    cancel: 'キャンセル',
    exportSuccess: 'エクスポート成功！',
    exportError: 'エクスポート失敗',
  },
  ko_KR: {
    save: '저장',
    pageBreak: '페이지 나누기',
    headerFooter: '머리글 및 바닥글',
    exportPdf: 'PDF 내보내기',
    exportDocx: 'DOCX 내보내기',
    pageSettings: '페이지 설정',
    pageSize: '페이지 크기',
    header: '머리글',
    footer: '바닥글',
    pageNumbers: '페이지 번호',
    pageNumberPosition: '페이지 번호 위치',
    none: '없음',
    left: '왼쪽',
    center: '가운데',
    right: '오른쪽',
    apply: '적용',
    cancel: '취소',
    exportSuccess: '내보내기 성공!',
    exportError: '내보내기 실패',
  },
  zh_CN: {
    save: '保存',
    copyMarkdown: '复制 Markdown',
    copyHtml: '复制 HTML',
    resetConfig: '重置配置',
    resetConfirm: '确定要重置 markdown-editor 的配置么?',
    pageBreak: '分页符',
    headerFooter: '页眉和页脚',
    exportPdf: '导出 PDF',
    exportDocx: '导出 DOCX',
    pageSettings: '页面设置',
    pageSize: '页面大小',
    header: '页眉',
    footer: '页脚',
    pageNumbers: '页码',
    pageNumberPosition: '页码位置',
    none: '无',
    left: '左',
    center: '居中',
    right: '右',
    apply: '应用',
    cancel: '取消',
    exportSuccess: '导出成功！',
    exportError: '导出失败',
  },
}

export const lang = (() => {
  let l: any = navigator.language.replace('-', '_')
  if (!Langs[l]) {
    l = 'en_US'
  }
  return l
})()

export function t(msg: string) {
  return (Langs[lang] && Langs[lang][msg]) || Langs.en_US[msg]
}
